# Generated by Django 5.1.4 on 2024-12-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="last_name",
            field=models.CharField(default="user", max_length=100),
        ),
    ]
