# Generated by Django 5.1.4 on 2024-12-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_author_last_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="image_name",),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(null=True, upload_to="posts"),
        ),
    ]
